/*
 * This file is generated by jOOQ.
*/
package xyz.tinystock.database;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import xyz.tinystock.database.tables.Component;
import xyz.tinystock.database.tables.Customer;
import xyz.tinystock.database.tables.Order;
import xyz.tinystock.database.tables.OrderDetail;
import xyz.tinystock.database.tables.Stock;
import xyz.tinystock.database.tables.User;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Stockdb extends SchemaImpl {

    private static final long serialVersionUID = -369406917;

    /**
     * The reference instance of <code>stockdb</code>
     */
    public static final Stockdb STOCKDB = new Stockdb();

    /**
     * The table <code>stockdb.COMPONENT</code>.
     */
    public final Component COMPONENT = xyz.tinystock.database.tables.Component.COMPONENT;

    /**
     * The table <code>stockdb.CUSTOMER</code>.
     */
    public final Customer CUSTOMER = xyz.tinystock.database.tables.Customer.CUSTOMER;

    /**
     * The table <code>stockdb.ORDER</code>.
     */
    public final Order ORDER = xyz.tinystock.database.tables.Order.ORDER;

    /**
     * The table <code>stockdb.ORDER_DETAIL</code>.
     */
    public final OrderDetail ORDER_DETAIL = xyz.tinystock.database.tables.OrderDetail.ORDER_DETAIL;

    /**
     * The table <code>stockdb.STOCK</code>.
     */
    public final Stock STOCK = xyz.tinystock.database.tables.Stock.STOCK;

    /**
     * The table <code>stockdb.USER</code>.
     */
    public final User USER = xyz.tinystock.database.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Stockdb() {
        super("stockdb", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Component.COMPONENT,
            Customer.CUSTOMER,
            Order.ORDER,
            OrderDetail.ORDER_DETAIL,
            Stock.STOCK,
            User.USER);
    }
}
