/*
 * This file is generated by jOOQ.
 */
package xyz.tinystock.database;


import javax.annotation.processing.Generated;

import xyz.tinystock.database.tables.Component;
import xyz.tinystock.database.tables.Customer;
import xyz.tinystock.database.tables.Order;
import xyz.tinystock.database.tables.OrderDetail;
import xyz.tinystock.database.tables.Stock;
import xyz.tinystock.database.tables.User;


/**
 * Convenience access to all tables in stockdb
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>stockdb.COMPONENT</code>.
     */
    public static final Component COMPONENT = xyz.tinystock.database.tables.Component.COMPONENT;

    /**
     * The table <code>stockdb.CUSTOMER</code>.
     */
    public static final Customer CUSTOMER = xyz.tinystock.database.tables.Customer.CUSTOMER;

    /**
     * The table <code>stockdb.ORDER</code>.
     */
    public static final Order ORDER = xyz.tinystock.database.tables.Order.ORDER;

    /**
     * The table <code>stockdb.ORDER_DETAIL</code>.
     */
    public static final OrderDetail ORDER_DETAIL = xyz.tinystock.database.tables.OrderDetail.ORDER_DETAIL;

    /**
     * The table <code>stockdb.STOCK</code>.
     */
    public static final Stock STOCK = xyz.tinystock.database.tables.Stock.STOCK;

    /**
     * The table <code>stockdb.USER</code>.
     */
    public static final User USER = xyz.tinystock.database.tables.User.USER;
}
